@extends('layouts.app')

@section('content')
    <div class="space-y-4">
        <div><h1 class="text-xl font-semibold text-gray-800 dark:text-white/90">Membership SaaS</h1><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Ringkasan seluruh akun yang menggunakan platform.</p></div>
        @if (session('success'))<div class="rounded-lg border border-success-200 bg-success-50 px-4 py-3 text-sm text-success-700">{{ session('success') }}</div>@endif
        <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            @foreach ([['Member', $summary['members']], ['Aktif', $summary['active']], ['Trial', $summary['trial']], ['Pendapatan', 'Rp'.number_format($summary['revenue'], 0, ',', '.')]] as [$label, $value])
                <div class="rounded-xl border border-gray-200 bg-white p-4 dark:border-gray-800 dark:bg-white/[0.03]"><p class="text-xs text-gray-500 dark:text-gray-400">{{ $label }}</p><p class="mt-2 text-xl font-semibold text-gray-900 dark:text-white">{{ $value }}</p></div>
            @endforeach
        </section>
        <div class="overflow-x-auto rounded-xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]"><table class="w-full min-w-[980px] text-left"><thead><tr class="border-b border-gray-100 text-[11px] uppercase text-gray-500 dark:border-gray-800"><th class="px-4 py-3">Member</th><th class="px-4 py-3">Paket</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Berakhir</th><th class="px-4 py-3 text-right">Pendapatan</th><th class="px-4 py-3">Kontrol akses</th></tr></thead><tbody>@foreach ($members as $member)<tr class="border-b border-gray-100 text-sm dark:border-gray-800"><td class="px-4 py-3"><p class="font-semibold text-gray-800 dark:text-white/90">{{ $member['owner']->name }}</p><p class="text-xs text-gray-500">{{ $member['owner']->email }}</p></td><td class="px-4 py-3">{{ $member['plan'] }}</td><td class="px-4 py-3">{{ $member['status'] }}</td><td class="px-4 py-3">{{ $member['period_ends_at'] ?: '-' }}@if($member['override_until'])<span class="block text-xs text-warning-600">Override sampai {{ $member['override_until']->format('Y-m-d') }}</span>@endif</td><td class="px-4 py-3 text-right">Rp{{ number_format($member['revenue'], 0, ',', '.') }}</td><td class="px-4 py-3"><div class="flex flex-wrap gap-2"><form method="POST" action="{{ route('superadmin.memberships.extend', $member['owner']->id) }}" class="flex gap-1">@csrf<input name="days" type="number" min="1" max="3650" value="30" class="h-8 w-16 rounded border px-2 text-xs"><input name="reason" required placeholder="Alasan" class="h-8 w-28 rounded border px-2 text-xs"><button class="rounded bg-brand-500 px-2 text-xs font-semibold text-white">+ Hari</button></form><form method="POST" action="{{ route('superadmin.memberships.bypass', $member['owner']->id) }}" class="flex gap-1">@csrf<input name="reason" required placeholder="Alasan bypass" class="h-8 w-28 rounded border px-2 text-xs"><button class="rounded bg-warning-500 px-2 text-xs font-semibold text-white">Bypass</button></form>@if($member['override_until'])<form method="POST" action="{{ route('superadmin.memberships.override.revoke', $member['owner']->id) }}">@csrf @method('DELETE')<button class="rounded border border-error-200 px-2 text-xs font-semibold text-error-600">Cabut</button></form>@endif</div></td></tr>@endforeach</tbody></table></div>
    </div>
@endsection
